language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install --upgrade memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: Dju0/yqEPRHCYs6eYKaFkQAluu43b90tQRouBCEnQOswX7zTCP9eSpE1EUvxBBRdy+8tVOqUNq2FzA/sE5hu3seoEVkNx07CI7TIKiTOpS/t3he50DuuFkbfNZ8ZiK/JDP9DnJZ8K0M7CYNIBliPcRiOdd+y8b/TQ63UIh7nZKq1RGMdVdOYh/vWvC8LUhr/GJJ7vChh5wuLF2NFFDu2OOC/ng9h8SzhN3mviT+MTaGoxSUAhlq+VCk68BFBjR2a6h3bWUBwYAOTTMm5tf96dYNeMaBDQHw7dOsxBPURQDlE6Me1mB3VUFfUsX+ruwnhpy1Oj0jNa2/ozghRRCeMwAouu5k+K/2/g6Zv6CRE4lQ4aeffToPq1xEuSVBxq9wQFDtKp56RkbKHg3PGSCbzUA+n5cv5eraHxR36iPQr9RgjZfsMlQPkT5dSgJGtLGc9jN930YhtBXowNau0lEbTnezgMkxDafwlmOkiG5NI77yFACao43/tma4Vn+kFAbTtcritHvt/x/qaaHBfZQyy6VVYBBkGZmch+RnS3ISt+B6g4VQM0ibIctkCYXuzfZsqfNQrL9YqQkufPPhaPHKg19i1acTPTr3lfnoW3CbHozMhZwORv7l70goniBH758JluZhQPtrD3qNmGwP8FLNSQWVcBa3m3VDKlYWJVMLnL6o=
