language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install --upgrade memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: ctt7Ri14ji69gRvlkZQekuCIpRPPYuA5y/9GOGcVb+HETjsuk4fD+OjfrZckRQSEtRTKGrUlSNS6UI5OIT+OxZHwFIWcnZifVswXk3m0QXbRblmdLhMuGYkZaqmkfqClahXu0yeVMTWMaUuhmvCMrBP7x2BYd+S/fsSBiuY/+GgYcBvwXL4s08LxhJ6TbDFm7Gy97d+KF2Ti6NMw015/ZFe9nDbDd0sFoJ45b/3TdEREMxf8QHGKEYERGkZ/OyjhNVZO3LQ4CUhcwOjhnKym5FQrOsbVgvptx0HjLXvs39U+GgQ+/QdaWy9gq+b77vgG/caT1R+KyTs08zdljhWzPh5B1JENVfE77WXtpHLVUssWnqZO1avvytZ/ML4u6II7d6ZK+AzSw2b367lUChklLQ/1eeEdizzn3s6yDJzltUazVmIl94WXKF82xwKGH4dQxIEStCjM7g+QnyQCRgiyGM2MxmY21IQyEeAJYcufAZB8DUwk6QyKfeyZNPD5eJt4d7gWojCLv5SqmGDE9T/ujKOG3i4mUhT/zxpgtR49osLxVIA3X3AqYCwmQl8CksisewohD+cQHsQAdwCuoHCOQI6tTRTrC5Yrd2+C4nxdUZMZWgv9gRo3af/MYSy3LzDafexzSHWy4Y9m2X/gGU0HJa0E2SVxfNOOKmSTHgc9g7k=
