language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install --upgrade memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: MM4mhlU4ahWTvphQtIhiKzdXiybfN+wOUks0whmRN2+jzwXZUcjt1C63m+jEE/vPCRSGL0rpZjSVBrPBmVV4vSHVklakqKumASYOs8c27NcJbBubWZdMrlNNdnCFqSZz53Q7pp8jsZKU/Y7ymkZRCEpIlOGwEs/Rn42+IxqqJQrBUU6TCavyrO6j9J3o8W5vkfTVg4fFMMliF5cpeJreuXCtkWjGmuPQRtpfUVqXZiLXyepg2M4H+WanE0BJJBf/ax98z0ysnm4+Tq46Rkn6qksvyqevVjVO3NeRNeMk/8boQChZz1vefftQF2XMXY8vgRYuaUT3RCLp/jhtdzlU78lBNP9ww/YacuvhjQxRwT47suWhzB+VkEN7UDhRUChpuZPsvVFYtC+Huo10ziddnthoouBdQT9y3g8Zl7HyZmuxdhA8CwllQb2o+uxnoQoSfJgZvzaBjNaxt/cx22yO8VgTbtWNBB84YF32SrfANxQaqUj7dW9twUnGDGnI+0AHRoSrLdCY182Kv4TtPDHsfFdlwWuhpWz8Oed4GZeLXleSGIOuu4zPzSNYxlrh0Uz1AmhnuYaV1/ilUcBcCbwIj+BzZLalszWueicJ4TWbVgkXkbYmh7y84HpxancTs737zNvvxNe1tPPeuBvGvKbm3LPO1bkUzm8i8vB0iZWInJE=
