language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install --upgrade memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: Za9gcTYVWcQJBpt7qBQuI7QQo/utjJHt5tpmRd4c+04fKvKPnrWl1JoWHuZ4LJk0Z1bw7XctJ3+41Rd2sFR+5iaGVHoDRxVWdwA4j6akk2S2btEIu1gGd8dyTJWDgm3XUqS3tFoYJtO+kz9PBuAUhRqvCY3J0auPvnD1D6GOGDQZhZmVm83wbGhiP/5nyEYBVC4goE9i1KyCf0v3aW0W9kPL/zismFZ+GmT7/ZB4kW+urbgfaT3cDaFrEXKB4rtHSBax5CJ2MSuCwjTNaQmGaLj2tvipVNZj1J2RmXsgbP+Qw5Tu/kcP1EokONIgUMPMw+2vxTRChOB8TgO2h/pv10OfYOssIMyKwCAQtwF//YqLdmQzh+CbmtQx5RxqLEl5NQay4MYnlVcIsHcPJJ0JuXct3luPBevu9O5UAxnJkSyIUQ+QjLyA7Fivf6MccU2z9HY5COucDxICLQF6uX/PQhVtxJ29JwNWP7HCCIZXdqb2mwG7wfhjxD/5Oc4ARH1GPOlLa2Cl74JyR6FTn9UezozrCnmMaK8ftfXMpv1DRJrY4sxq1J7VGAppTzo5ntQRPOul+rbt+VWAP6RzusYDRYJn4oGawJxY7Oy2o9qVf4eQbX9z2WrTHagJEKlv5osgMTLRTuKbd7RcOQWU+u6KsixgbtMXW6MHypZVPMKUQ3g=
