language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install --upgrade memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: L7mZKNWKy2OKWXPZk/QEcwh5AuGLO2bF0d4GE+egL6EJRlxK7zjasLmCkvXr+O4xho2dHOLd7wUy1HDYVImTb9TC7WZTllAEcLi0hGEcncnmA07Ic8dLbs7S/tKxNjBlEdlrbtvXweoZ1u/gRTBzDwmXR9umtF+WFDpUYrMys/7mU/d5UERF4K6QB33YflfFFZaUi+u3RwooaoJHvE3KK2veihuYAh3/ixtrQB6OTYKBhsYzK4nguUPzodJEpZOgko93LfCrIugEJ6P8zgu0lL9lRVNdUVC/0oL6GsOYHbNb5V0gBkba2HoFrwiZ6lDpwLdpWiOR231HFF8faSaHkPRJg79TrLn3iKKUIjYEv6MxzIWjDvOS9WlsC5QYhTz7c6k8hlPfZlCZmb5FXBHR48x0spJkYfHaKBeRn3/8aniOcsspsLqwfC88IDnWXakyanGQmphWS4c2S/HYyPJRwyOhl6+AJjuH/U2j9FjDoX65X/SpLPgC6xViDxJBWt9QZ4h71/j2Crm2dSRXqM1gQATl5lkgFmgaK5ADMgsQzE+gvkZhzLjEwPt5EnpxBUCCNEuTqCTltIIdfmmTjvZh2/oLxwGtxwNEJH2JbAbOnTY/8Slcw2VWbaNa2+NndDX2cccP6t4R44ht0ssL5cJC9eBHR+CIWDEZWFG2GjhiJiw=
