language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install --upgrade memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: OJO+g0B/p/hhSU4DgYkdkbUc713iCTufNHAQItJDLrHXkQsRJo4o88bAB2+QkIK90S9PDp8jj5NpQBFF2p+hacTjlwbA1HhHIbQ5D+bOK2VT5Srfuj9CrWC2X996mzLDt8w0r5P+hQBJGdppsAtIadRDr1kmR7au2f3tL2uF6tUIxgyQHR2TNDIQ2lcoOmniJ5GffSMPtpilO6t+vnzxVYHND1AWAcjqMTv9fKngXpWLhXXB00boMfFBg2wWEaqq+6KnO+V4PMUDG7Waq2Jy/7LdLtvatFuX38OLu+5G5lX2pXDc+W6vQP2F2uPS1dixE/p7pyS9qjCAMX6r5jMewzG80SzelIsvVMFKdGw47xzhN65fkpAWlobkX/gAAWW8+1/Wcc7kONKS5uLRzbRKxDu0c7jNApYRT2GPurNhXWamagmZ0ET1fOKeSEn/dnRH+6idKECpWw+ajcY9edEceE7lpDQbZAhIbHJ5fhu4d0lfBjhNfl13EOLlCa/Lt5ywlZKC/sNqX5mwAuZ8xCc+DSskhC+UhgjwzNZ5AUy0MKin/43sQfDddEeBYnsXURb8MhW3qWMmAUiKKrnTUxFuuX4So6gs+H22iOCFvo6negq5m5xyuVQ2Sz7AAwhR30najb7ujUAyI+mIh/UB0fK+U0WPtc5q1K63uor/rzV5uhs=
